<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GradeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('grades')->insert([
            [
                'name'=>'7A',
                'teacher'=>'',
            ],
            [
                'name'=>'7B',
                'teacher'=>'',
            ],
            [
                'name'=>'7C',
                'teacher'=>'',
            ],
            [
                'name'=>'7D',
                'teacher'=>'',
            ],
            [
                'name'=>'7E',
                'teacher'=>'',
            ],
            [
                'name'=>'7F',
                'teacher'=>'',
            ],
            [
                'name'=>'7G',
                'teacher'=>'',
            ],
            [
                'name'=>'7H',
                'teacher'=>'',
            ],
            [
                'name'=>'7I',
                'teacher'=>'',
            ],
            [
                'name'=>'7J',
                'teacher'=>'',
            ],
            [
                'name'=>'7K',
                'teacher'=>'',
            ],
            [
                'name'=>'7L',
                'teacher'=>'',
            ],
            [
                'name'=>'7M',
                'teacher'=>'',
            ],
            [
                'name'=>'7N',
                'teacher'=>'',
            ],
            [
                'name'=>'7O',
                'teacher'=>'',
            ],
            [
                'name'=>'7P',
                'teacher'=>'',
            ],
            [
                'name'=>'7Q',
                'teacher'=>'',
            ],
            [
                'name'=>'7R',
                'teacher'=>'',
            ],
            [
                'name'=>'7S',
                'teacher'=>'',
            ],
            [
                'name'=>'7T',
                'teacher'=>'',
            ],
            [
                'name'=>'7U',
                'teacher'=>'',
            ],
            [
                'name'=>'7V',
                'teacher'=>'',
            ],
            [
                'name'=>'7W',
                'teacher'=>'',
            ],
            [
                'name'=>'7X',
                'teacher'=>'',
            ],
            [
                'name'=>'7Y',
                'teacher'=>'',
            ],
            [
                'name'=>'7Z',
                'teacher'=>'',
            ],
        ]);
    }
}
